### ISSUE TITLE
Fusion weapons

### ISSUE THREAD

**Issue by Liquidous** [Neocron-Classic/pre-release-issues#148] opened 2022-09-16 22:52 UTC
When firing Fusion weapons the starburst graphic that surround the projectile will stay inplace infront of the weapon and float there.. After a few clips there can be a bunch ..

AMD 6800Xt
Incase you needed card info

**Comment by Jestunhi** [comment] 2022-10-23 09:34
Closed as duplicate of #23 - this does apply to more than just the NPCs in the earlier report, however that one includes screenshots, etc so I'll keep that one open and close this one.

**Closed by Jestunhi** 2022-10-23 09:34 UTC
Labels: duplicate
