### ISSUE TITLE
UI Stacks overlapping

### ISSUE THREAD

**Issue by thejohnwick** [Neocron-Classic/pre-release-issues#30] opened 2022-09-04 14:39 UTC
![unknown](https://user-images.githubusercontent.com/36860966/188319089-563834e1-576b-4e79-a752-637b6ef41412.png)

**Comment by NCC-Lykos** [comment] 2022-09-04 16:59
Duplicate of https://github.com/Neocron-Classic/pre-release-issues/issues/21

**Closed by NCC-Lykos** 2022-09-04 16:59 UTC
