### ISSUE TITLE
Sewer Map visual bug

### ISSUE THREAD

**Issue by Skansy** [Neocron-Classic/pre-release-issues#236] opened 2022-11-01 21:31 UTC
## The problem
Mapping bug, no transperency

![image](https://user-images.githubusercontent.com/32749567/199345558-f6e49da2-8cb3-4c43-b276-cb9fa9c80178.png)

**Comment by Jestunhi** [comment] 2022-11-01 21:43
Closed as duplicate of #101

**Closed as completed by Jestunhi** 2022-11-01 21:43 UTC
