### ISSUE TITLE
Spells: Healing and Buffs do not cast when moving too much/too fast.

### ISSUE THREAD

**Issue by ForeverToast** [Neocron-Classic/pre-release-issues#42] opened 2022-09-05 00:55 UTC
Tested with TL3 Crahn Deflector and TL3 Crahn Heal.

If the player is moving too much and or too fast while casting a heal or buff spell the spell will not be cast. Tested while Running and Walking.

Tested on self and on other Runners, Same result.

Occurred 10/10.

https://user-images.githubusercontent.com/22384196/188340838-3f624c04-3b96-4973-87cb-f2199080742e.mp4

https://user-images.githubusercontent.com/22384196/188340964-be3399d1-91fe-4c5e-bf3c-72a19be3dca6.mp4

**Comment by hazuk** [comment] 2022-09-05 03:36
you a tank with a not build spell?? thats normal get better spells or more skill points in psy

**Comment by Dreaminpastels** [comment] 2022-09-05 09:16
Hazuk is right, this is intended. Though I don't remember in NC1 what PSI Use, MST and PPU skill do exactly in regards to spell casting.

**Comment by NCC-Lykos** [comment] 2022-09-05 15:51
Closed as intended. You cannot runcast store bought spells without the skill to cap them.

**Closed by NCC-Lykos** 2022-09-05 15:51 UTC
