### ISSUE TITLE
Stam Booster Cannot Be Used

### ISSUE THREAD

**Issue by EvilHogg** [Neocron-Classic/pre-release-issues#153] opened 2022-09-18 22:37 UTC
Some stam boosters cannot be used. See attached screenshot. The stam booster on the right cannot be used.  The booster was obtained from a mob, possibly an aggressor or aggressor cpt.

![stam_booster_cant_be_used](https://user-images.githubusercontent.com/34963912/190930770-7b32694e-1bb0-4efb-9a9f-1471ff20afec.png)

Same with medkit.

![medkit](https://user-images.githubusercontent.com/34963912/190936028-ee056511-4e29-419f-b3f3-4dac8dcaf0b6.png)

**Comment by Jestunhi** [comment] 2022-09-19 00:37
It's caused by gen repping (or dying) and possibly sometimes from zoning.

It's hopefully resolved in the upcoming item storage update: https://github.com/Neocron-Classic/pre-release-issues/issues/34

**Comment by NCC-Gnisha** [comment] 2022-09-20 04:17
Duplicate of #34

**Closed by NCC-Gnisha** 2022-09-20 04:17 UTC
