### ISSUE TITLE
Terminal: Clan Info bugs

### ISSUE THREAD

**Issue by Wilworin** [Neocron-Classic/pre-release-issues#105] opened 2022-09-11 20:20 UTC
Whatever I try, I can't find a single clan inside INFO->CLAN:
![image](https://user-images.githubusercontent.com/75475031/189547160-d77eebec-f85e-4c01-8ece-d0ca080e296a.png)

But when I check INFO->OUTPOST it's obvious that there has to be atleast one clan:
![image](https://user-images.githubusercontent.com/75475031/189547197-f01c9c8c-1c34-463c-bac2-55aafdb94aa9.png)

Now comes the next bug though. When I press on one of the outposts it won't fetch the name of the clan that owns it but it just says: "_- scanning -_".
![image](https://user-images.githubusercontent.com/75475031/189547226-335ec160-870b-42c2-81a4-be000e800b02.png)

It all makes me wondering. Is the terminal failing to fetch the clans or have the clan been deleted after it took all OPs? If it's the second then I would have assumed that all OPs would have gotten free again but nothing is for certain. :)

**Comment by NCC-Gnisha** [comment] 2022-09-11 21:20
This is not a bug, it's user error.

Top right of the screen is a filter, it will not show you any clans unless it has that many or more members. The clan you're referencing as 1 member.

Not a bug. Closing.

**Closed by NCC-Gnisha** 2022-09-11 21:20 UTC
