### ISSUE TITLE
Trading window missmatch at 2.0 scale

### ISSUE THREAD

**Issue by tuxhomer** [Neocron-Classic/pre-release-issues#132] opened 2022-09-14 17:35 UTC
![shot0014](https://user-images.githubusercontent.com/13179348/190223987-731eb5b8-cd37-41a1-b2eb-74b9bf02791b.png)

**Comment by NCC-Gnisha** [comment] 2022-09-15 00:37
Duplicate of #74

**Closed by NCC-Gnisha** 2022-09-15 00:37 UTC
