### ISSUE TITLE
Graphic error with the sellers Yo's ect.

### ISSUE THREAD

**Issue by antiteilchen** [Neocron-Classic/pre-release-issues#74] opened 2022-09-07 17:15 UTC
Graphic error with sellers, occurs with Yo's and with other sellers.
The error comes unexpectedly and can only be fixed with a restart.

https://user-images.githubusercontent.com/113052035/188939146-cbf08cb7-0423-428b-8850-7c81fe0d81a1.mp4

https://user-images.githubusercontent.com/113052035/188939461-ed121f5a-132e-4cbe-a48c-d3acc3ee0259.mp4

**Comment by NCC-Gnisha** [comment] 2022-09-07 21:20
Are you running multiple clients?

**Comment by antiteilchen** [comment] 2022-09-08 10:51
> * What resolution are you running at?
> 
>     * Are you running multiple clients?

"* What resolution are you running at?"
2560x1440 32

"* Are you running multiple clients?"
No

**Comment by Jestunhi** [comment] 2022-09-08 21:21
Have you changed the scaling of RPOS elements in settings.toml, if so what have you changed them to.

**Comment by hazuk** [comment] 2022-09-09 22:18
> Have you changed the scaling of RPOS elements in settings.toml, if so what have you changed them to.

looke like 1.5....
i got 1.4 and it happens sometimes to me too at 2560*1440

**Comment by antiteilchen** [comment] 2022-09-13 11:24
> Have you changed the scaling of RPOS elements in settings.toml, if so what have you changed them to.

Sorry for the late answer, i changed the settings.TOML.
From standard to 1.5 / 2560*1440

LOOK!

[rpos]
	[rpos.scale]
		VEHICLESEAT = 1.5
		SKILL = 1.5
		NAVRAYWINDOW = 1.5
		HYPERCOM = 1.5
		RESPAWNWINDOW = 1.5
		INVENTORY = 1.5
		ARMOR = 1.5
		TARGETBOX = 1.5
		MISSIONINFO = 1.5
		MISCWINDOW = 1.5
		EXITAPPARTMENT = 1.5
		DIALOG = 1.5
		IMPLANTS = 1.5
		TOOLTIP = 1.5
		TEAMWINDOW = 1.5
		NAVRAYARROW = 1.5
		NAVRAYPATH = 1.5
		TUTORIAL = 1.5
		STATUS = 1.5
		CURSOR = 1.5
		QUICKACCESS = 1.5
		BOTTOMBAR_VERTICAL = 1.5
		TOPBAR_VERTICAL = 1.5
		CHAT = 1.5
		PEOPLE = 1.5
		PROCESSOR = 1.5
		QUICKTIPS = 1.5
		SPLITMOVE = 1.5
		REPLICATORWINDOW = 1.5
		CROSSHAIR = 1.5
		ZONEMAP = 1.5
		COMPASS = 1.5
		MINIMAP = 1.5
		MENUBAR = 1.5
		CONTAINER = 1.5
		VEHICALSTATUS = 1.5
		GOGO = 1.5
		HELPTEXTWINDOW = 1.5
		TERMINAL = 1.5
		BUFF = 1.5
		ENTERCODE = 1.5
		FACTIONS = 1.5
		TRADE = 1.5
		PLAYERTRADE = 1.5
		RCLICKMENU = 1.5
[misc]
	language = "GER"
	last-server = 0
	last-char = 0
[chat]
	quick-messages = ["first sms here", "second here", "etc", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
[input]
	sensitivity = 0.29
	rpos-movement = false
	invert-mouse = false
[display]
	driver = "(D3D9) NVIDIA GeForce GTX 760"
	resolution = "."
	mode = "2560x1440x32"
[sound]
	music-volume = 0.0
	fx-volume = 0.19
	music-enabled = false
	fx-enabled = true
	[sound.device]
		driver = "Generic DirectSound Driver"
		mixer = "Generic DirectSound Mixer"
[graphics]
	gamma = 1.0
	vegetation-distance = 1.0
	object-lod-distance-factor = 1.0
	fog-distance = 1.0

**Comment by hazuk** [comment] 2022-09-14 19:18
how to make bug visable
1. Login
2. Disconnect
3.Change Account
4.Log back in with other Account
5.Bug shows up
can Reproduce it with these steps every time

**Comment by Jestunhi** [comment] 2022-10-22 08:28
Closed as duplicate of #31

**Closed by Jestunhi** 2022-10-22 08:28 UTC
